**R Programming apply family of functions**

In this experiment we will learn about how to use apply family of functions
to do data wrangling and avaoid use of looping constructs 

The R base manual tells you that it’s called as follows: 

```
apply(X, MARGIN, FUN, ...)
```


```X``` is an array or a matrix if the dimension of the array is ```2```

```MARGIN``` is a variable defining how the function is applied: 
 

*   When ```MARGIN=1```, it applies over rows 
*   Whereas with ```MARGIN=2```, it works over columns
*   ```MARGIN=c(1,2)```, it applies to both rows and columns;     

and
```FUN```, represents the function that you want to apply to the data. It can be any R function, including a User Defined Function (UDF).

In [1]:
# Complete the following code by using apropriate apply family function
# Construct a 5x6 matrix
X <-matrix(rnorm(30), nrow=5, ncol=6)
X





[,1]       [,2]       [,3]       [,4]        [,5]       [,6]       
[1,]  1.0280596  1.0731702 -0.9333935 -1.02386970 -0.6977347  0.41290850
[2,]  1.3100591  0.6127682  0.4314712  1.81672520  0.6181652  1.05897350
[3,]  1.3508136 -0.6905205 -0.6880943 -2.87077582 -0.2709282 -0.09918477
[4,] -1.6257865 -0.7278499 -0.1236284 -0.39065727 -1.5487372 -1.33622036
[5,]  0.2366202  1.1232852 -0.4682073 -0.06365649 -0.2624893  0.48107174

In [2]:
# Sum the values of each column with apply()
X_colsum <- apply(X,2,sum)
X_colsum

[1]  2.2997660  1.3908532 -1.7818524 -2.5322341 -2.1617242  0.5175486

In [3]:
# Sum the values of each row with apply()
X_rowsum <- apply(X,1,sum)
X_rowsum

[1] -0.1408597  5.8481624 -3.2686900 -5.7528796  1.0466240

The **lapply()** Function is used when You want to apply a given function to every element of a list and obtain a list as a result.
 
 Syntax of **lapply()** looks like the **apply()** function.

There is a slight difference in way they work, which is :



1.   **lapply()** can be used for other objects like dataframes, lists or vectors
2.   The output returned by **lapply()** is a list (which explains the “l” in the function name), which has the same number of elements as the object passed to it.

To see how this works, complete the following code block.

**lapply()** is a quite common operation performed on real data when making comparisons or aggregations from different dataframes.


In [4]:
# Using sequence 1:9 create a matrix A with size 3*3
A <- matrix(1:9, nrow=3, ncol=3)
A 

















[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [5]:
#Using sequence 4:15 create a matrix B with size 4*3
B <- matrix(4:15, nrow=4, ncol=3)
B

[,1] [,2] [,3]
[1,] 4     8   12  
[2,] 5     9   13  
[3,] 6    10   14  
[4,] 7    11   15

In [6]:
#Using sequnce 8:10 create a matrix C with size 3*2
C <- matrix(8:10, nrow=3, ncol=2)
C

[,1] [,2]
[1,]  8    8  
[2,]  9    9  
[3,] 10   10

In [7]:
# create variable MyList as list of matrix A, B, C
MyList <- list(A, B, C)
MyList

[[1]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[2]]
     [,1] [,2] [,3]
[1,]    4    8   12
[2,]    5    9   13
[3,]    6   10   14
[4,]    7   11   15

[[3]]
     [,1] [,2]
[1,]    8    8
[2,]    9    9
[3,]   10   10

In [8]:
# Using lapply and [ operator Extract the 2nd column from `MyList` with the selection operator `[` with `lapply()`
lapply(MyList, '[', , 2)

[[1]]
[1] 4 5 6

[[2]]
[1]  8  9 10 11

[[3]]
[1]  8  9 10

In [9]:
# Using lapply and [ operator Extract the 4th row from `MyList` with the selection operator `[` with `lapply()`
lapply(MyList, '[', 4, )
# Error Occurs because in MyList there are 3 matrix where matrix A and C is having only 3 rows!!!

ERROR: ignored

In [10]:
# Using lapply and [ operator Extract the 1st row from `MyList` with the selection operator `[` with `lapply()`
lapply(MyList, '[', 1, )

[[1]]
[1] 1 4 7

[[2]]
[1]  4  8 12

[[3]]
[1] 8 8

The **sapply()** Function

The **sapply()** function works like **lapply()**, but it tries to simplify the output to the most elementary data structure that is possible. And indeed, ```sapply()``` is a **‘wrapper’** function for **lapply()**.

Let’s repeat the extraction operation of a single element as in the last example, but now take the first element of the second row (indexes 2 and 1) for each matrix.

Applying the **lapply()** function would give us a list unless you pass ```simplify=FALSE``` as a parameter to **sapply()**. Then, a list will be returned. See how it works in the code chunk below:



In [11]:
# Return a list with `lapply()`
lapply(MyList,"[", 2, 1 )

# Return a vector with `sapply()`
sapply(MyList,"[", 2, 1 )

# Return a list with `sapply()`
sapply(MyList,"[", 2, 1, simplify=F)

# Return a vector with `unlist()`
unlist(lapply(MyList,"[", 2, 1 ))

[[1]]
[1] 2

[[2]]
[1] 5

[[3]]
[1] 9

[1] 2 5 9

[[1]]
[1] 2

[[2]]
[1] 5

[[3]]
[1] 9

[1] 2 5 9

In this Text Block Write note on mapply function and give exampe code and exaplain use of mapply function.

1.The arguments for mapply are mapply(FUN, …, MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE). First you list the function, followed by the vectors you are using the rest of the arguments have default values so they don’t need to be changed for now. When you have a function that takes 2 arguments, the first vector goes into the first argument and the second vector goes into the second argument.  


Example use of Mapply Function

##### Example 1
In this example, 1:9 is specifying the value to repeat, and 9:1 is specifying how many times to repeat. This order is based on the order of arguments in the rep function itself.

In [12]:
# Example use of mapply function
 mapply(rep, 1:9, 9:1)

[[1]]
[1] 1 1 1 1 1 1 1 1 1

[[2]]
[1] 2 2 2 2 2 2 2 2

[[3]]
[1] 3 3 3 3 3 3 3

[[4]]
[1] 4 4 4 4 4 4

[[5]]
[1] 5 5 5 5 5

[[6]]
[1] 6 6 6 6

[[7]]
[1] 7 7 7

[[8]]
[1] 8 8

[[9]]
[1] 9

##### Example 2
Another use for mapply would be to create a new variable. For example, using  dataset t, I could divide one column by another column to create a new value. This would be useful for creating a ratio of two variables as shown in the example below.

In [13]:
my.matrx <- matrix(c(1:10, 11:20, 21:30), nrow = 10, ncol = 3)
tdata <- as.data.frame(cbind(c(1,1,1,1,1,2,2,2,2,2), my.matrx))

tdata$V5<- mapply(function(x, y) x/y, tdata$V2, tdata$V4)
tdata$V5

[1] 0.04761905 0.09090909 0.13043478 0.16666667 0.20000000 0.23076923
 [7] 0.25925926 0.28571429 0.31034483 0.33333333

##### Example 3
When using an apply family function to create a new variable, one option is to create a new vector ahead of time with the size of the vector pre-allocated. I created a numeric vector of length 10 using the vector function. The arguments for the vector function are vector(mode, length). Inside mapply I created a function to multiple two variables together. The results of the mapply function are then saved into the vector.

In [14]:
new.vec <- vector(mode = "numeric", length = 10)
new.vec <- mapply(function(x, y) x*y, tdata$V3, tdata$V4)
new.vec

[1] 231 264 299 336 375 416 459 504 551 600